import { PrismaClient, ExamType } from '@prisma/client';

const prisma = new PrismaClient();

const GATE_CS_SYLLABUS = {
  'Engineering Mathematics': [
    'Mathematical Logic',
    'Propositional Logic',
    'Sets Theory',
    'Relations',
    'Functions',
    'Counting Theory',
    'Graph Theory',
    'Propositional Logic',
    'Matrices',
    'Linear Algebra',
    'Calculus',
    'Limits',
    'Continuity',
    'Differentiability',
    'Integration',
    'Differential Equations',
    'Vector Calculus',
    'Probability and Statistics',
    'Random Variables',
    'Distributions',
    'Mean',
    'Median',
    'Mode',
    'Variance',
    'Standard Deviation',
  ],
  'Digital Logic': [
    'Boolean Algebra',
    'Logic Gates',
    'K-Map',
    'Minimization',
    'Combinational Circuits',
    'Adders',
    'Subtractors',
    'Multiplexers',
    'Demultiplexers',
    'Encoders',
    'Decoders',
    'Sequential Circuits',
    'Flip-Flops',
    'Registers',
    'Counters',
    'Memory Units',
  ],
  'Computer Organization and Architecture': [
    'Data Representation',
    'Number Systems',
    'Fixed Point',
    'Floating Point',
    'Machine Instructions',
    'Instruction Formats',
    'Addressing Modes',
    'Instruction Set Architecture',
    'ALU Design',
    'Control Unit Design',
    'Pipelining',
    'Hazards',
    'Memory Hierarchy',
    'Cache Memory',
    'Main Memory',
    'Virtual Memory',
    'I/O Organization',
  ],
  'Programming and Data Structures': [
    'C Programming',
    'Pointers',
    'Arrays',
    'Strings',
    'Functions',
    'Recursion',
    'Structures',
    'Linked Lists',
    'Singly Linked List',
    'Doubly Linked List',
    'Circular Linked List',
    'Stacks',
    'Stack Operations',
    'Stack Applications',
    'Queues',
    'Queue Types',
    'Priority Queues',
    'Trees',
    'Binary Trees',
    'Binary Search Trees',
    'AVL Trees',
    'B Trees',
    'B+ Trees',
    'Heaps',
    'Hashing',
    'Collision Resolution',
    'Graphs',
    'Graph Representations',
    'Traversals',
  ],
  'Algorithms': [
    'Asymptotic Analysis',
    'Time Complexity',
    'Space Complexity',
    'Recurrence Relations',
    'Sorting Algorithms',
    'Bubble Sort',
    'Selection Sort',
    'Insertion Sort',
    'Merge Sort',
    'Quick Sort',
    'Heap Sort',
    'Searching',
    'Linear Search',
    'Binary Search',
    'Divide and Conquer',
    'Greedy Method',
    'Dynamic Programming',
    'Knapsack',
    ' LCS',
    'Graph Algorithms',
    'BFS',
    'DFS',
    "Dijkstra's Algorithm",
    'Bellman Ford',
    'Floyd Warshall',
    'MST',
    'Prim\'s Algorithm',
    "Kruskal's Algorithm",
    'NP-Completeness',
    'P vs NP',
    'NP-Hard',
    'NP-Complete',
  ],
  'Theory of Computation': [
    'Finite Automata',
    'DFA',
    'NFA',
    'Regular Expressions',
    'Regular Languages',
    'Properties',
    'Pumping Lemma',
    'Context-Free Grammar',
    'CFG',
    'Pushdown Automata',
    'PDA',
    'Context-Free Languages',
    'Properties',
    'Chomsky Normal Form',
    'Greibach Normal Form',
    'Turing Machines',
    'TM Variants',
    'Undecidability',
    'Halting Problem',
    'Rice Theorem',
    'Recursively Enumerable',
  ],
  'Compiler Design': [
    'Lexical Analysis',
    'Tokens',
    'Regular Expressions',
    'Finite Automata',
    'Lexical Analyzers',
    'Syntax Analysis',
    'Parsing',
    'Top-Down Parsing',
    'Recursive Descent',
    'Predictive Parsing',
    'Bottom-Up Parsing',
    'LR Parser',
    'SLR',
    'LALR',
    'Canonical LR',
    'Semantic Analysis',
    'Type Checking',
    'Symbol Table',
    'Intermediate Code Generation',
    'Three Address Code',
    'Code Optimization',
    'Basic Blocks',
    'Loops',
    'Code Generation',
    'Register Allocation',
  ],
  'Operating System': [
    'Process Management',
    'Process States',
    'PCB',
    'Scheduling',
    'FCFS',
    'SJF',
    'Round Robin',
    'Priority Scheduling',
    'Synchronization',
    'Mutual Exclusion',
    'Semaphores',
    'Monitors',
    'Deadlock',
    'Prevention',
    'Avoidance',
    'Detection',
    'Recovery',
    'Memory Management',
    'Paging',
    'Segmentation',
    'Virtual Memory',
    'Page Replacement',
    'LRU',
    'FIFO',
    'Optimal',
    'File Systems',
    'Directory Structure',
    'File Allocation',
    'Disk Scheduling',
    'I/O Systems',
  ],
  'Databases': [
    'ER Model',
    'Entities',
    'Attributes',
    'Relationships',
    'ER Diagrams',
    'Relational Model',
    'Relations',
    'Keys',
    'Integrity Constraints',
    'Relational Algebra',
    'Select',
    'Project',
    'Join',
    'Union',
    'Intersection',
    'Difference',
    'Cartesian Product',
    'SQL',
    'DDL',
    'DML',
    'DCL',
    'Queries',
    'Joins',
    'Subqueries',
    'Views',
    'Normalization',
    '1NF',
    '2NF',
    '3NF',
    'BCNF',
    'Transactions',
    'ACID Properties',
    'Concurrency Control',
    'Locking',
    'Timestamp',
    'Recovery',
  ],
  'Computer Networks': [
    'Network Models',
    'OSI Model',
    'TCP/IP Model',
    'Physical Layer',
    'Transmission Media',
    'Data Link Layer',
    'Framing',
    'Error Detection',
    'CRC',
    'Flow Control',
    'Network Layer',
    'IP Addressing',
    'Subnetting',
    'Routing Algorithms',
    'RIP',
    'OSPF',
    'BGP',
    'Transport Layer',
    'TCP',
    'UDP',
    'Flow Control',
    'Congestion Control',
    'Application Layer',
    'HTTP',
    'FTP',
    'DNS',
    'SMTP',
    'Network Security',
    'Cryptography',
    'Firewalls',
  ],
  'General Aptitude': [
    'Verbal Ability',
    'Synonyms',
    'Antonyms',
    'Analogies',
    'Sentence Completion',
    'Word Usage',
    'Paragraph Formation',
    'Critical Reasoning',
    'Facts Inference Judgment',
    'Numerical Ability',
    'Number System',
    'Percentages',
    'Profit and Loss',
    'Ratio and Proportion',
    'Time and Work',
    'Time Speed and Distance',
    'Averages',
    'Simple Interest',
    'Compound Interest',
    'Permutation and Combination',
    'Probability',
    'Data Interpretation',
    'Tables',
    'Bar Graphs',
    'Line Graphs',
    'Pie Charts',
    'Caselets',
  ],
};

async function main() {
  console.log('Seeding GATE CS Syllabus...');

  // Create CS Branch
  const csBranch = await prisma.branch.upsert({
    where: { code: 'CS' },
    update: {},
    create: {
      name: 'Computer Science and Information Technology',
      code: 'CS',
      examType: ExamType.GATE,
    },
  });
  console.log('Created Branch: CS');

  // Create Subject for GATE CS
  const subjectNames = Object.keys(GATE_CS_SYLLABUS);
  
  for (const subjectName of subjectNames) {
    const subject = await prisma.subject.upsert({
      where: { 
        code_examType: { 
          code: subjectName.toUpperCase().replace(/\s+/g, '_').substring(0, 10),
          examType: ExamType.GATE,
        }
      },
      update: {},
      create: {
        name: subjectName,
        code: subjectName.toUpperCase().replace(/\s+/g, '_').substring(0, 10),
        examType: ExamType.GATE,
        branchCode: 'CS',
      },
    });

    // Create Syllabus
    const syllabus = await prisma.syllabus.upsert({
      where: { id: `gate-cs-${subjectName.toLowerCase().replace(/\s+/g, '-')}` },
      update: {},
      create: {
        id: `gate-cs-${subjectName.toLowerCase().replace(/\s+/g, '-')}`,
        title: `GATE CS - ${subjectName}`,
        description: `Official GATE Computer Science - ${subjectName} syllabus`,
        subjectId: subject.id,
        examType: ExamType.GATE,
        branchCode: 'CS',
        isPublished: true,
        sourceType: 'SYLLABUS',
      },
    });

    // Create Units and Topics
    const topics: string[] = GATE_CS_SYLLABUS[subjectName as keyof typeof GATE_CS_SYLLABUS];
    
    // Split topics into groups of ~6 for units
    const unitSize = 6;
    const unitCount = Math.ceil(topics.length / unitSize);
    
    for (let u = 0; u < unitCount; u++) {
      const unitTopics = topics.slice(u * unitSize, (u + 1) * unitSize);
      
      const unit = await prisma.unit.create({
        data: {
          title: `Unit ${u + 1}`,
          order: u + 1,
          syllabusId: syllabus.id,
        },
      });

      for (let t = 0; t < unitTopics.length; t++) {
        await prisma.topic.create({
          data: {
            title: unitTopics[t],
            order: t + 1,
            unitId: unit.id,
            examType: ExamType.GATE,
            branchCode: 'CS',
          },
        });
      }
    }

    console.log(`Created: ${subjectName} with ${topics.length} topics`);
  }

  console.log('GATE CS Syllabus seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });