import { PrismaClient, QuestionType } from '@prisma/client';

const prisma = new PrismaClient();

interface Q {
  question: string;
  options: { index: number; text: string }[];
  correctAnswer: number;
  correctNumeric?: string;
  explanation?: string;
  marks: number;
  negativeMarks: number;
  difficulty: string;
  questionType: QuestionType;
  branch: string;
  subject: string;
  tags: string[];
}

const ALL_QUESTIONS: Q[] = [
  { question: 'Which data structure is best suited for implementing recursion?', options: [{ index: 0, text: 'Queue' }, { index: 1, text: 'Stack' }, { index: 2, text: 'Linked List' }, { index: 3, text: 'Heap' }], correctAnswer: 1, explanation: 'Stack uses LIFO principle which mirrors function call stack for recursion.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'The worst case time complexity of Quick Sort is:', options: [{ index: 0, text: 'O(n)' }, { index: 1, text: 'O(log n)' }, { index: 2, text: 'O(n log n)' }, { index: 3, text: 'O(n²)' }], correctAnswer: 3, explanation: 'Quick Sort worst case O(n²) when pivot is always smallest or largest element.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'How many edges are present in a complete graph with 8 vertices?', options: [], correctAnswer: 0, correctNumeric: '28', explanation: 'Complete graph K₈ has n(n-1)/2 = 8×7/2 = 28 edges.', marks: 1, negativeMarks: 0, difficulty: 'EASY', questionType: 'NAT', branch: 'CS', subject: 'Engineering Mathematics', tags: ['CS', 'Engineering Mathematics', 'GATE'] },
  { question: 'In a max-heap with n elements, the time complexity to find the maximum element is:', options: [{ index: 0, text: 'O(1)' }, { index: 1, text: 'O(log n)' }, { index: 2, text: 'O(n)' }, { index: 3, text: 'O(n log n)' }], correctAnswer: 0, explanation: 'Max element is at root (index 0), directly accessible in O(1).', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'What is the time complexity of searching in a balanced BST?', options: [{ index: 0, text: 'O(log n)' }, { index: 1, text: 'O(n)' }, { index: 2, text: 'O(n log n)' }, { index: 3, text: 'O(1)' }], correctAnswer: 0, explanation: 'Balanced BST has height O(log n), so search takes O(log n) time.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'A singly linked list has a cycle. Which algorithm can detect it?', options: [{ index: 0, text: "Floyd's cycle detection" }, { index: 1, text: 'Binary search' }, { index: 2, text: 'Merge sort' }, { index: 3, text: "Dijkstra's algorithm" }], correctAnswer: 0, explanation: "Floyd's tortoise and hare algorithm uses slow and fast pointers to detect cycles.", marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'The number of leaf nodes in a complete binary tree of height h is:', options: [{ index: 0, text: '2^h' }, { index: 1, text: '2^(h+1) - 1' }, { index: 2, text: '2^(h-1)' }, { index: 3, text: 'h + 1' }], correctAnswer: 0, explanation: 'A complete binary tree of height h has 2^h leaf nodes.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Data Structures', tags: ['CS', 'Data Structures', 'GATE'] },
  { question: 'The worst case time complexity of Merge Sort is:', options: [{ index: 0, text: 'O(n log n) in all cases' }, { index: 1, text: 'O(n²) in worst case' }, { index: 2, text: 'O(n log n) in average, O(n²) in worst' }, { index: 3, text: 'O(n) in best case' }], correctAnswer: 0, explanation: 'Merge Sort always divides the array in half and merges in linear time, giving O(n log n) for all cases.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'Which algorithm uses a min-heap for implementation?', options: [{ index: 0, text: "Prim's algorithm" }, { index: 1, text: "Kruskal's algorithm only" }, { index: 2, text: "Dijkstra's algorithm only" }, { index: 3, text: "Both Prim's and Kruskal's" }], correctAnswer: 0, explanation: "Prim's algorithm uses a min-heap to select the minimum weight edge. Kruskal's uses union-find.", marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: "The recurrence T(n) = 2T(n/2) + n has solution:", options: [{ index: 0, text: 'Θ(n log n)' }, { index: 1, text: 'Θ(n)' }, { index: 2, text: 'Θ(n²)' }, { index: 3, text: 'Θ(log n)' }], correctAnswer: 0, explanation: 'By Master theorem: a=2, b=2, f(n)=n, n^(log_b a)=n^1=n. Case 2: f(n)=Θ(n^log_b a * log n) = Θ(n log n).', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: "In Dijkstra's algorithm, what data structure is typically used?", options: [{ index: 0, text: 'Min-priority queue' }, { index: 1, text: 'Stack' }, { index: 2, text: 'Queue' }, { index: 3, text: 'Linked list' }], correctAnswer: 0, explanation: "Dijkstra's algorithm uses a min-priority queue to efficiently extract the minimum distance vertex.", marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'Which search algorithm has worst-case O(log n) complexity?', options: [{ index: 0, text: 'Binary search' }, { index: 1, text: 'Linear search' }, { index: 2, text: 'Jump search' }, { index: 3, text: 'Interpolation search' }], correctAnswer: 0, explanation: 'Binary search halves the search space each time, giving O(log n) worst case.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'The time complexity of finding the shortest path using Bellman-Ford algorithm is:', options: [{ index: 0, text: 'O(V×E)' }, { index: 1, text: 'O(V+E)' }, { index: 2, text: 'O(V²)' }, { index: 3, text: 'O(E log V)' }], correctAnswer: 0, explanation: 'Bellman-Ford relaxes all edges V-1 times, giving O(V×E) time complexity.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'Which of the following is not a stable sorting algorithm?', options: [{ index: 0, text: 'Heap Sort' }, { index: 1, text: 'Merge Sort' }, { index: 2, text: 'Bubble Sort' }, { index: 3, text: 'Insertion Sort' }], correctAnswer: 0, explanation: 'Heap Sort is not stable. Merge, Bubble, and Insertion sort are stable.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'The solution to the 0/1 knapsack problem using dynamic programming has time complexity:', options: [{ index: 0, text: 'O(n×W)' }, { index: 1, text: 'O(2^n)' }, { index: 2, text: 'O(n+W)' }, { index: 3, text: 'O(n²)' }], correctAnswer: 0, explanation: 'DP solution for 0/1 knapsack uses a 2D table of size n×W, giving O(n×W) complexity.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Algorithms', tags: ['CS', 'Algorithms', 'GATE'] },
  { question: 'Which of the following languages is context-free?', options: [{ index: 0, text: '{a^n b^n c^n | n ≥ 1}' }, { index: 1, text: '{ww | w ∈ {a,b}*}' }, { index: 2, text: '{a^n b^n | n ≥ 1}' }, { index: 3, text: '{a^n | n is prime}' }], correctAnswer: 2, explanation: '{a^n b^n} is context-free. {ww} and {a^n b^n c^n} are not context-free.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'TOC', tags: ['CS', 'TOC', 'GATE'] },
  { question: 'The language L = {ww^R | w ∈ {a,b}*} is:', options: [{ index: 0, text: 'Regular' }, { index: 1, text: 'Context-free but not regular' }, { index: 2, text: 'Context-sensitive' }, { index: 3, text: 'Recursively enumerable' }], correctAnswer: 0, explanation: '{ww^R} is regular — we can build a DFA that accepts it by reading input and checking palindrome property.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'TOC', tags: ['CS', 'TOC', 'GATE'] },
  { question: 'Which of the following is a known undecidable problem?', options: [{ index: 0, text: 'Post Correspondence Problem' }, { index: 1, text: 'Checking if a number is prime' }, { index: 2, text: 'Finding shortest path in a graph' }, { index: 3, text: 'Sorting a list of numbers' }], correctAnswer: 0, explanation: 'Post Correspondence Problem (PCP) is undecidable. Primality testing, shortest path, and sorting are all decidable.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'TOC', tags: ['CS', 'TOC', 'GATE'] },
  { question: 'A language recognized by a Pushdown Automata (PDA) is:', options: [{ index: 0, text: 'Context-free' }, { index: 1, text: 'Regular' }, { index: 2, text: 'Context-sensitive' }, { index: 3, text: 'Recursive' }], correctAnswer: 0, explanation: 'PDA recognizes exactly context-free languages.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'TOC', tags: ['CS', 'TOC', 'GATE'] },
  { question: 'The number of states in the minimum DFA for the language L = {a^n b^m | n,m ≥ 0} is:', options: [{ index: 0, text: '2' }, { index: 1, text: '3' }, { index: 2, text: '4' }, { index: 3, text: '5' }], correctAnswer: 0, explanation: 'L accepts strings with any number of a\'s followed by any number of b\'s. 2 states: initial (also accepts empty string) and b-state.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'TOC', tags: ['CS', 'TOC', 'GATE'] },
  { question: 'Which of the following is NOT a phase of a compiler?', options: [{ index: 0, text: 'Code generator' }, { index: 1, text: 'Syntax analyzer' }, { index: 2, text: 'Intermediate code generator' }, { index: 3, text: 'Code optimizer' }], correctAnswer: 0, explanation: 'All except "Code generator" are standard compiler phases. Code generator is part of code generation phase.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Compiler Design', tags: ['CS', 'Compiler Design', 'GATE'] },
  { question: 'LR(1) parser is more powerful than LALR parser because:', options: [{ index: 0, text: 'LR(1) has more states than LALR' }, { index: 1, text: 'LALR merges LR(1) states' }, { index: 2, text: 'LALR has more states than LR(1)' }, { index: 3, text: 'They have the same power' }], correctAnswer: 1, explanation: 'LALR parser is constructed by merging LR(1) states. This can cause reduce-reduce conflicts that LR(1) does not have.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Compiler Design', tags: ['CS', 'Compiler Design', 'GATE'] },
  { question: 'In a bottom-up parser, the parse tree is built:', options: [{ index: 0, text: 'From leaves to root' }, { index: 1, text: 'From root to leaves' }, { index: 2, text: 'In random order' }, { index: 3, text: 'From middle to both ends' }], correctAnswer: 0, explanation: 'Bottom-up parsers start from input symbols (leaves) and reduce them to start symbol (root).', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Compiler Design', tags: ['CS', 'Compiler Design', 'GATE'] },
  { question: 'The output of the lexical analyzer is:', options: [{ index: 0, text: 'Sequence of tokens' }, { index: 1, text: 'Parse tree' }, { index: 2, text: 'Intermediate code' }, { index: 3, text: 'Machine code' }], correctAnswer: 0, explanation: 'Lexical analyzer (scanner) reads source code and produces a stream of tokens for the parser.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Compiler Design', tags: ['CS', 'Compiler Design', 'GATE'] },
  { question: 'The smallest unit of data that can be transferred between main memory and CPU is:', options: [{ index: 0, text: 'Word' }, { index: 1, text: 'Byte' }, { index: 2, text: 'Bit' }, { index: 3, text: 'Block' }], correctAnswer: 0, explanation: 'Word is the natural unit of data for a specific processor architecture. CPU transfers data word by word.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'COA', tags: ['CS', 'COA', 'GATE'] },
  { question: 'The CPU scheduling algorithm that minimizes average waiting time is:', options: [{ index: 0, text: 'SJF (Shortest Job First)' }, { index: 1, text: 'FCFS' }, { index: 2, text: 'Round Robin' }, { index: 3, text: 'Priority scheduling' }], correctAnswer: 0, explanation: 'SJF gives minimum average waiting time among non-preemptive algorithms.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'OS', tags: ['CS', 'OS', 'GATE'] },
  { question: 'In a deadlock situation, the four necessary conditions are simultaneously satisfied. Which of the following is NOT one of them?', options: [{ index: 0, text: 'Circular wait' }, { index: 1, text: 'Hold and wait' }, { index: 2, text: 'No preemption' }, { index: 3, text: 'Mutual exclusion' }], correctAnswer: 0, explanation: 'The four conditions are: Mutual exclusion, Hold and wait, No preemption, Circular wait. All are necessary for deadlock.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'OS', tags: ['CS', 'OS', 'GATE'] },
  { question: 'The file allocation method that avoids external fragmentation is:', options: [{ index: 0, text: 'Linked allocation' }, { index: 1, text: 'Contiguous allocation' }, { index: 2, text: 'Indexed allocation' }, { index: 3, text: 'Both linked and indexed' }], correctAnswer: 3, explanation: 'Linked allocation stores blocks scattered on disk, no external fragmentation. Indexed allocation also avoids it.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'OS', tags: ['CS', 'OS', 'GATE'] },
  { question: 'A process is in the blocked state. Which event will move it to the ready state?', options: [{ index: 0, text: 'I/O completion' }, { index: 1, text: 'CPU burst completion' }, { index: 2, text: 'Time quantum expiration' }, { index: 3, text: 'Context switch' }], correctAnswer: 0, explanation: 'Blocked process moves to ready when the event it was waiting for (like I/O completion) occurs.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'OS', tags: ['CS', 'OS', 'GATE'] },
  { question: 'Thrashing in an operating system occurs when:', options: [{ index: 0, text: 'Excessive paging activity degrades performance' }, { index: 1, text: 'CPU is idle' }, { index: 2, text: 'Memory is underutilized' }, { index: 3, text: 'Processes are terminated' }], correctAnswer: 0, explanation: 'Thrashing occurs when the system spends more time paging than executing processes.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'OS', tags: ['CS', 'OS', 'GATE'] },
  { question: 'Which normal form removes transitive dependency?', options: [{ index: 0, text: '3NF' }, { index: 1, text: '2NF' }, { index: 2, text: 'BCNF' }, { index: 3, text: '1NF' }], correctAnswer: 0, explanation: '3NF removes transitive dependencies. 2NF removes partial dependencies. BCNF is stricter than 3NF.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'DBMS', tags: ['CS', 'DBMS', 'GATE'] },
  { question: 'A transaction exhibits the property of durability meaning:', options: [{ index: 0, text: 'Once committed, changes persist despite failures' }, { index: 1, text: 'Operations are atomic' }, { index: 2, text: 'Concurrent execution is isolated' }, { index: 3, text: 'Database remains consistent' }], correctAnswer: 0, explanation: 'Durability guarantees that once a transaction commits, its effects survive system failures.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'DBMS', tags: ['CS', 'DBMS', 'GATE'] },
  { question: 'In a B+ tree, all keys are stored in:', options: [{ index: 0, text: 'Leaf nodes only' }, { index: 1, text: 'Internal nodes only' }, { index: 2, text: 'Both internal and leaf nodes' }, { index: 3, text: 'Root node only' }], correctAnswer: 0, explanation: 'In B+ tree, only leaf nodes contain actual data pointers. Internal nodes only contain keys for navigation.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'DBMS', tags: ['CS', 'DBMS', 'GATE'] },
  { question: 'Which layer in the OSI model handles routing?', options: [{ index: 0, text: 'Network layer' }, { index: 1, text: 'Data link layer' }, { index: 2, text: 'Transport layer' }, { index: 3, text: 'Session layer' }], correctAnswer: 0, explanation: 'Network layer (Layer 3) is responsible for routing packets across networks.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'CN', tags: ['CS', 'CN', 'GATE'] },
  { question: 'In TCP, the three-way handshake is used to:', options: [{ index: 0, text: 'Establish a connection' }, { index: 1, text: 'Terminate a connection' }, { index: 2, text: 'Send data' }, { index: 3, text: 'Flow control' }], correctAnswer: 0, explanation: 'Three-way handshake (SYN, SYN-ACK, ACK) establishes a reliable TCP connection.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'CN', tags: ['CS', 'CN', 'GATE'] },
  { question: 'The IP address 255.255.255.255 is:', options: [{ index: 0, text: 'Limited broadcast address' }, { index: 1, text: 'Loopback address' }, { index: 2, text: 'Network address' }, { index: 3, text: 'Multicast address' }], correctAnswer: 0, explanation: '255.255.255.255 is the limited broadcast address — delivered to all hosts on the local network.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'CN', tags: ['CS', 'CN', 'GATE'] },
  { question: 'Which protocol is used to resolve an IP address to a MAC address?', options: [{ index: 0, text: 'ARP' }, { index: 1, text: 'RARP' }, { index: 2, text: 'DHCP' }, { index: 3, text: 'DNS' }], correctAnswer: 0, explanation: 'ARP (Address Resolution Protocol) maps IP addresses to MAC addresses on a local network.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'CN', tags: ['CS', 'CN', 'GATE'] },
  { question: 'Let G be a simple undirected graph with n vertices. Which of the following statements is ALWAYS true?', options: [{ index: 0, text: 'If G is connected, then it has a spanning tree' }, { index: 1, text: 'If G has n-1 edges, then it is a tree' }, { index: 2, text: 'If G has no cycles, then it is a forest' }, { index: 3, text: 'If G is bipartite, then it is planar' }], correctAnswer: 0, explanation: 'A connected graph always has a spanning tree which is a subgraph containing all vertices.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Engineering Mathematics', tags: ['CS', 'Engineering Mathematics', 'GATE'] },
  { question: 'Eigenvalues of a symmetric matrix are all:', options: [{ index: 0, text: 'Real' }, { index: 1, text: 'Imaginary' }, { index: 2, text: 'Zero' }, { index: 3, text: 'Complex' }], correctAnswer: 0, explanation: 'A symmetric matrix always has real eigenvalues.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Engineering Mathematics', tags: ['CS', 'Engineering Mathematics', 'GATE'] },
  { question: 'If P(A) = 0.5, P(B) = 0.5 and P(A∪B) = 0.75, then P(A|B) is:', options: [{ index: 0, text: '0.5' }, { index: 1, text: '0.6' }, { index: 2, text: '0.75' }, { index: 3, text: '0.25' }], correctAnswer: 0, explanation: 'P(A∪B) = P(A) + P(B) - P(A∩B), so 0.75 = 0.5 + 0.5 - P(A∩B), P(A∩B) = 0.25. P(A|B) = P(A∩B)/P(B) = 0.25/0.5 = 0.5', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Engineering Mathematics', tags: ['CS', 'Engineering Mathematics', 'GATE'] },
  { question: 'If the price of a book is reduced by 20%, it becomes Rs. 240. The original price (in Rs.) was:', options: [{ index: 0, text: '300' }, { index: 1, text: '280' }, { index: 2, text: '320' }, { index: 3, text: '260' }], correctAnswer: 0, explanation: '80% of original = 240, Original = 240 × 100/80 = 300.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'General Aptitude', tags: ['CS', 'General Aptitude', 'GATE'] },
  { question: 'Find the missing number: 2, 6, 12, 20, 30, ?', options: [{ index: 0, text: '42' }, { index: 1, text: '40' }, { index: 2, text: '38' }, { index: 3, text: '44' }], correctAnswer: 0, explanation: 'Differences: 4,6,8,10,12. Pattern: n² + n. So 6² + 6 = 42.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'General Aptitude', tags: ['CS', 'General Aptitude', 'GATE'] },
  { question: 'A train 100m long passes a platform 150m long in 10 seconds. The speed of the train (in m/s) is:', options: [{ index: 0, text: '25' }, { index: 1, text: '20' }, { index: 2, text: '15' }, { index: 3, text: '10' }], correctAnswer: 0, explanation: 'Distance covered = train length + platform length = 100 + 150 = 250m. Speed = 250/10 = 25 m/s.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'General Aptitude', tags: ['CS', 'General Aptitude', 'GATE'] },
  { question: 'A man walks 30 km towards south, then turns right and walks 20 km. He then turns right and walks 30 km. In which direction is he now?', options: [{ index: 0, text: 'North' }, { index: 1, text: 'South' }, { index: 2, text: 'East' }, { index: 3, text: 'West' }], correctAnswer: 1, explanation: 'South → right turn (west) → right turn (north). He faces north.', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'General Aptitude', tags: ['CS', 'General Aptitude', 'GATE'] },
  { question: 'The minimum number of 2-input NAND gates required to implement the function f = x + yz is:', options: [{ index: 0, text: '3' }, { index: 1, text: '4' }, { index: 2, text: '5' }, { index: 3, text: '6' }], correctAnswer: 1, explanation: 'f = x + yz = NAND(NAND(x, x), NAND(y, z)) = 4 NAND gates minimum.', marks: 1, negativeMarks: 0.33, difficulty: 'MEDIUM', questionType: 'MCQ', branch: 'CS', subject: 'Digital Logic', tags: ['CS', 'Digital Logic', 'GATE'] },
  { question: 'The output of a 2-input XOR gate is 1 when:', options: [{ index: 0, text: 'Exactly one input is 1' }, { index: 1, text: 'Both inputs are 1' }, { index: 2, text: 'Both inputs are 0' }, { index: 3, text: 'At least one input is 1' }], correctAnswer: 0, explanation: 'XOR output is 1 when inputs are different (exactly one input is 1).', marks: 1, negativeMarks: 0.33, difficulty: 'EASY', questionType: 'MCQ', branch: 'CS', subject: 'Digital Logic', tags: ['CS', 'Digital Logic', 'GATE'] },
];

async function seedQuestions() {
  let saved = 0;
  let failed = 0;

  for (const q of ALL_QUESTIONS) {
    try {
      await prisma.mCQ.create({
        data: {
          question: q.question,
          options: q.options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation || null,
          difficulty: q.difficulty as any,
          examType: 'GATE',
          marks: q.marks,
          negativeMarks: q.negativeMarks,
          questionType: q.questionType,
          gateBranchCode: q.branch,
          tags: q.tags,
          sourceType: 'OFFICIAL_PAPER',
          isPreviousYear: true,
        },
      });
      saved++;
      if (saved % 10 === 0) console.log(`Saved ${saved}...`);
    } catch (err) {
      console.error('Failed:', err);
      failed++;
    }
  }
  return { saved, failed };
}

async function main() {
  console.log('Clearing existing MCQs...');
  await prisma.mCQAttempt.deleteMany({});
  await prisma.mCQ.deleteMany({});
  
  console.log('Seeding questions...');
  const result = await seedQuestions();
  
  console.log(`\n✅ Done! Saved: ${result.saved}, Failed: ${result.failed}`);
  
  const count = await prisma.mCQ.count();
  console.log(`Total MCQs in DB: ${count}`);
  
  await prisma.$disconnect();
}

main().catch(console.error);